[env:seeed_xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino

build_flags =
    -DNIMBLE_DEBUG_DISABLED
    -DCORE_DEBUG_LEVEL=0
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -DCONFIG_BT_NIMBLE_ENABLED=1

upload_speed = 921600
monitor_speed = 115200
monitor_filters = esp32_exception_decoder

lib_deps =
    h2zero/NimBLE-Arduino@^2.0.0
    mathieucarbou/ESP Async WebServer@^3.0.6
    adafruit/Adafruit NeoPixel@^1.12.0
